# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Adrian "asie" Siekierka, 2024

BLOCKSDS	?= /opt/wonderful/thirdparty/blocksds/core
BLOCKSDSEXT ?= /opt/wonderful/thirdparty/blocksds/external

# User config

NAME		:= Silly_Test2
GAME_TITLE	:= Angle_Calculation
GAME_SUBTITLE	:= Input

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile